### ISSUE TITLE
Issue when globally installing Tezster

### ISSUE THREAD

**Issue by sean-magin** [Tezsure/Tezster-GUI#144]
<img width="564" alt="Screen Shot 2020-09-15 at 5 37 05 PM" src="https://user-images.githubusercontent.com/14209806/93169846-22321600-f77a-11ea-98b0-ad201e4b1a5b.png">

I've hit an issue when installing Tezster globally. I ran the command as super user too.

**Comment by aditya-tezsure** [comment]
@sean-magin Hello this seems to be the issue on tezster-CLI can you please raise it on the same.
Although, there are few dependencies like hardware wallet in conseil.js which requires root permission.
for better clarification, you can have a one on one with our developers on the telegram link: [https://t.me/tezster](https://t.me/tezster)
